import Item from '@/components/Item'
import Head from 'next/head'
import { addDoc, collection, deleteDoc, onSnapshot, orderBy, query, doc } from "firebase/firestore"
import { db } from "../utils/firebase"
import { useEffect, useState } from 'react'

export default function Home() {
  const [allPosts, setAllPosts] = useState([])
  
  const getPosts = async () =>{
    const collectionRef =  collection(db, 'dontdos')
    const q = query(collectionRef)
    const unsubscribe =  onSnapshot(q, (snapshot) =>  {
      setAllPosts(snapshot.docs.map((doc) => ({...doc.data(), id: doc.id})))
    })
    return unsubscribe
  }


  const deletePosts =  async (id) => {
    const docRef =  doc(db, 'dontdos', id)
    await deleteDoc(docRef)
  }



  useEffect(() => {
    getPosts()
  }, [])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='w-full h-screen grid grid-cols-3 gap-4 content-center'>
        {
          allPosts?.map((post) => (
            <Item {...post}>
                <div className="flex gap-2">
                  <button onClick={() => deletePosts(post.id)} className="bg-red-400 text-white p-2 text-sm rounded-md">Delete Item</button>
                  <button className="bg-green-400 text-white p-2 text-sm rounded-md">Edit Item</button>
                </div>
            </Item>
          ))

        }
      </main>
    </div>
  )
}
